airflow-worker-0.airflow-worker.airflow.svc.cluster.local
*** Log file does not exist: /opt/airflow/logs/dag_id=kubernetes_sample/run_id=manual__2023-04-13T02:17:39.632365+00:00/task_id=passing-task/attempt=1.log
*** Fetching from: http://airflow-worker-0.airflow-worker.airflow.svc.cluster.local:8793/log/dag_id=kubernetes_sample/run_id=manual__2023-04-13T02:17:39.632365+00:00/task_id=passing-task/attempt=1.log

[2023-04-13T02:17:41.890+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: kubernetes_sample.passing-task manual__2023-04-13T02:17:39.632365+00:00 [queued]>
[2023-04-13T02:17:41.900+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: kubernetes_sample.passing-task manual__2023-04-13T02:17:39.632365+00:00 [queued]>
[2023-04-13T02:17:41.901+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T02:17:41.901+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-04-13T02:17:41.901+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T02:17:41.914+0000] {taskinstance.py:1300} INFO - Executing <Task(KubernetesPodOperator): passing-task> on 2023-04-13 02:17:39.632365+00:00
[2023-04-13T02:17:41.920+0000] {standard_task_runner.py:55} INFO - Started process 901 to run task
[2023-04-13T02:17:41.924+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'kubernetes_sample', 'passing-task', 'manual__2023-04-13T02:17:39.632365+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/twopods_dag.py', '--cfg-path', '/tmp/tmppc4izv4e']
[2023-04-13T02:17:41.925+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask passing-task
[2023-04-13T02:17:42.039+0000] {task_command.py:388} INFO - Running <TaskInstance: kubernetes_sample.passing-task manual__2023-04-13T02:17:39.632365+00:00 [running]> on host airflow-worker-0.airflow-worker.airflow.svc.cluster.local
[2023-04-13T02:17:42.166+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=kubernetes_sample
AIRFLOW_CTX_TASK_ID=passing-task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T02:17:39.632365+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T02:17:39.632365+00:00
[2023-04-13T02:17:42.181+0000] {kubernetes_pod.py:675} INFO - Building pod passing-test-6llva0fk with labels: {'dag_id': 'kubernetes_sample', 'task_id': 'passing-task', 'run_id': 'manual__2023-04-13T021739.6323650000-708389fce', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2023-04-13T02:17:42.275+0000] {kubernetes_pod.py:454} INFO - Found matching pod passing-test-6llva0fk with labels {'airflow_kpo_in_cluster': 'True', 'airflow_version': '2.5.1', 'dag_id': 'kubernetes_sample', 'foo': 'bar', 'kubernetes_pod_operator': 'True', 'run_id': 'manual__2023-04-13T021739.6323650000-708389fce', 'task_id': 'passing-task', 'try_number': '1'}
[2023-04-13T02:17:42.275+0000] {kubernetes_pod.py:455} INFO - `try_number` of task_instance: 1
[2023-04-13T02:17:42.275+0000] {kubernetes_pod.py:456} INFO - `try_number` of pod: 1
[2023-04-13T02:17:42.286+0000] {pod_manager.py:187} WARNING - Pod not yet started: passing-test-6llva0fk
[2023-04-13T02:17:43.297+0000] {pod_manager.py:187} WARNING - Pod not yet started: passing-test-6llva0fk
[2023-04-13T02:17:44.310+0000] {pod_manager.py:187} WARNING - Pod not yet started: passing-test-6llva0fk
[2023-04-13T02:17:45.319+0000] {pod_manager.py:187} WARNING - Pod not yet started: passing-test-6llva0fk
[2023-04-13T02:17:46.330+0000] {pod_manager.py:187} WARNING - Pod not yet started: passing-test-6llva0fk
[2023-04-13T02:17:47.349+0000] {pod_manager.py:235} INFO - MySQL connection established!
[2023-04-13T02:17:47.381+0000] {kubernetes_pod.py:550} INFO - Deleting pod: passing-test-6llva0fk
[2023-04-13T02:17:47.454+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=kubernetes_sample, task_id=passing-task, execution_date=20230413T021739, start_date=20230413T021741, end_date=20230413T021747
[2023-04-13T02:17:47.495+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-04-13T02:17:47.526+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check

